
n_clusters: 16
n_neighbors: 10

epochs: 100
lr: 0.0005
batch_size: 64
loss: "scan"  # One of scan, supervised

embedding_type: "cls_token"  # One of cls_token, patch_tokens, soft_masked_patch_tokens


hydra:
#   job:
#     chdir: True
  
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}