
n_clusters: 16
n_estimated_neighbors: 10

epochs: 100
lr: 0.001
batch_size: 64
loss: "scan"  # One of scan, cross_entropy
scan_entropy_weight: 1.0

embedding_type: "zoom_cls_tokens"  # One of cls_tokens, zoom_cls_tokens, patch_tokens


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}