
n_clusters: 16
n_estimated_neighbors: 10

epochs: 100
lr: 0.0001
batch_size: 64
loss: "scan"  # One of scan, ce
scan_entropy_weight: 1.0

embedding_type: "cls_tokens"  # One of the files in embeddings/


hydra:
#   job:
#     chdir: True
  
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}